export const NAVIGATION_ROUTES = {
  USER_DASHBOARD: "/",
  DASHBOARD: "/admin/dashboard",
  LOGIN: "/login",
  SIGNUP: "/signup",
  MEMBER_MANAGEMENT: "/member-management",
  VOUCHER: "/voucher",
  REPORT: "/report",
  MASTER: "/master",
  CONFIGURATION: "/configuration",
  SETTINGS: "/settings",
  PRODUCTS: "/products",
  PROPERTY: "/property",
  MEMBERTIER: "/member-tier",
  SETPASSWORD: "/set-password/:token",
  SUCCESS: "/success",
  PROFILE_DETAIL: "/profile-detail",
  SERVICE: "/service",
  USER_PROFILE: "/profile-edit",
  FORGOT_PASSWORD: "/forgot-password",
};
