export const NAVIGATION_ROUTES = {
  USER_DASHBOARD: "/",
  DASHBOARD: "/admin/dashboard",
  LOGIN: "/login",
  SIGNUP: "/signup",
  MEMBER_MANAGEMENT: "/member-management",
  VOUCHER: "/voucher",
  MASTER: "/master",
  CONFIGURATION: "/configuration",
  SETTINGS: "/settings",
  PRODUCTS: "/products",
  PROPERTY: "/property",
  MEMBER_TIER: "/member-tier",
  SET_PASSWORD: "/set-password/:token",
  SUCCESS: "/success",
  PROFILE_DETAIL: "/profile-detail",
  SERVICE: "/service",
  BONUS: "/bonus",
  USER_PROFILE: "/profile-edit",
  FORGOT_PASSWORD: "/forgot-password",
  VOUCHER_ADD: "/voucher/add",
  OFFER: "/offers",
  STAFF_MANAGEMENT: "/staff-management",
  NOT_FOUND: "/not-found",
  HISTORY: "/history",
  USER_REPORT: "/user-report",
};
