export const NAVIGATION_ROUTES = {
  USER_DASHBOARD: "/",
  DASHBOARD: "/admin/dashboard",
  LOGIN: "/login",
  SIGNUP: "/signup",
  MEMBER_MANAGEMENT: "/member-management",
  VOUCHER: "/voucher",
  REPORT: "/report",
  MASTER: "/master",
  CONFIGURATION: "/configuration",
  SETTINGS: "/settings",
  PRODUCTS: "/products",
  PROPERTYS: "/propertys",
  PROPERTY: "/property",
  MEMBERTIER: "/member-tier",
  SETPASSWORD: "/set-password",
  SUCCESS: "/success",
};
